Api
frontend-park-mail-ru/2024_2_RPO pull request #13
Opened 2024-10-31 21:02 UTC by KoSafronov

2024-11-01 10:43 UTC, F4lkr4m requested changes

2024-11-01 10:43 UTC, F4lkr4m commented on src/.gitignore
> +config.ts
Не надо убирать в гитигнор конфиг, разместите просто дефолтный конфиг

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
> +  if (requestBody !== undefined) {
`if (requestBody)`

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
> +        let returnValue: any;
Стоп, почему any? Давайте стараться без any писать код

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
> +        if (contentType.includes('application/json')) {
`const returnValue = contentType.includes('application/json') ? JSON.parse(text) : text;`

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
> +      return response.text().then((text) => {
Используйте `response.json()`

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
> +const fetchApi = (
Сделайте функцию асинхронной и пишите код синхронно

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
> +      if (response.status >= 400 && response.status < 600) {
Константы для кодов ответов

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
> +      return response.text().then((text: string) => {
Повторение кода, что сверху

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
>    if (contentType === 'application/json') {
'application/json' как тип ответа в константу

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/apiHelper.ts
> +  if (newApiRoot === 'mock') {
`useMocks = newApiRoot === 'mock';`

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
> +        (el: BoardInfoResponse): Board => ({ id: el.id, title: el.name })
`json.map(({name, id}) => { id, name})`

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
>      const response = await apiGet(`/boards/${boardId}/allContent`);
Сразу доставайте данные `const { status, body } = await apiGet();`

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
> +      const columns: BoardColumn[] = boardContentResponse.allColumns.map(
Не, ребят, это архитектурно неправильно, у вас слой api не должен заниматься форматированием данных. Этим уже занимается service/model

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
> +      const columns: BoardColumn[] = boardContentResponse.allColumns.map(
Апи просто возвращает данные по вашему протоколу как транспорт. У вас могут быт разные апи, которые возвращают одно и то же

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
> +      const columns: BoardColumn[] = boardContentResponse.allColumns.map(
Апи - это транспорт, он может быть разный

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
> +    const updatedBoard: BoardResponse = response.body;
`const { id, name } = response.body `

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
> +      alert(`${action}: Board not found`);
Обрабатывать ошибками алертами - это ошибка) 
Бросайте ошибки и делайте try catch в модели, она будет отправлять тост и как то обрабатывать это дело

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
> +      alert(`${action}: Board not found`);
А также было бы круто создать логгер, который будет логгировать ваши ошибки запросов, но это задача со *

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/types.ts
> +  role: "viewer" | "editor" | "editor_chief" | "admin";
Создайте тип для роли:
`type Role = "viewer" | "editor" | "editor_chief" | "admin";`
И его переиспользуйте

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/boards.ts
> +      const columns: BoardColumn[] = boardContentResponse.allColumns.map(
Если будете делать форматирование данных, сразу делайте отдельный функции приводящие один тип к другому

2024-11-01 10:43 UTC, F4lkr4m commented on src/api/users.ts
> +    if (response.status === HTTP_STATUS_BAD_REQUEST) {
`if (response.status === HTTP_STATUS_BAD_REQUEST) {...}`

`if (response.status !== HTTP_STATUS_OK) {...}`
лишняя вложенность не нужна

2024-11-01 10:43 UTC, F4lkr4m commented on src/components/KanbanColumn.tsx
> +          textClassName="kanban-column__title"
Мешанина кавычек, используйте везде одинарные кавычки, заведите правило в линтере

2024-11-01 10:43 UTC, F4lkr4m commented on src/containers/KanbanBoard.tsx
> +  const activeBoardStore = useActiveBoardStore() as ActiveBoard;
Почему каждый раз приводить приходится к типу?

2024-11-01 10:43 UTC, F4lkr4m commented on src/containers/RegistrationDialog.tsx
> +// import { Button } from '@/components/Button';
Куча комментов?

2024-11-01 10:43 UTC, F4lkr4m commented on src/containers/RegistrationDialog.tsx
> +              if (data.password.length < 8) {
Константа

2024-11-01 10:43 UTC, F4lkr4m commented on src/routes/routesFlag.ts
>    console.log('Current path: ', currentPath);
Лог

2024-11-01 10:43 UTC, F4lkr4m commented on src/routes/routesFlag.ts
> +    if (currentPath.startsWith('/app/board_')) {
Ваши урлы на сайте должны выглядеть как `/app/board/{:id}/` и так далее
/app/board_123 это как минимум не красиво
Да и парсить другой вариант легче

2024-11-01 10:43 UTC, F4lkr4m commented on src/screens/MainApp.tsx
> +  if(boards===undefined){
`if (!boards) {}`

2024-11-01 10:43 UTC, F4lkr4m commented on src/screens/MainApp.tsx
> +  if(boards===undefined){
Забыли пробелы, не прогнали линтером

2024-11-01 10:43 UTC, F4lkr4m commented on src/stores/activeBoardStore.ts
> +  if (abStore !== undefined) {
`if (!abStore?.id === boardId) return`?

2024-11-01 10:45 UTC, DeDxYk594 commented on src/routes/routesFlag.ts
> +    if (currentPath.startsWith('/app/board_')) {
После РК будем думать, пока пусть остаётся так

2024-11-02 15:22 UTC, DeDxYk594 commented on src/api/apiHelper.ts
> +  if (requestBody !== undefined) {
А вдруг там будет какое-нибудь falsy значение, которое должно быть передано как plain/text?

2024-11-04 22:50 UTC, merged