Фронтенд готов к РК1
frontend-park-mail-ru/2024_2_RPO pull request #3
Opened 2024-09-29 14:30 UTC by DeDxYk594

2024-09-29 16:08 UTC, F4lkr4m requested changes
Ну в целом очень неплохо

2024-09-29 16:08 UTC, F4lkr4m commented on .prettierrc
Подготовьтесь к РК и ответьте себе на вопрос чем преттиер отличается от eslint

2024-09-29 16:08 UTC, F4lkr4m commented on README.md
> +
Добавьте список команды и менторов с ссылками на гитхабы

2024-09-29 16:08 UTC, F4lkr4m commented on dev_server/error_message.html
errorMessage и devServer

2024-09-29 16:08 UTC, F4lkr4m commented on dev_server/ts_compile.ts
> +import * as ts from "typescript";
Кавычки одинарные давайте

2024-09-29 16:08 UTC, F4lkr4m commented on server.ts
> +  if (name.endsWith('.js')) pathToFile = pathToBuild;
А где фигурные скобки?

2024-09-29 16:08 UTC, F4lkr4m commented on server.ts
> +  if (name.endsWith('.js')) pathToFile = pathToBuild;
Можно тернарник `pathToFile = name.endsWith('.js') ? pathToBuild : path.join('src', name)`

2024-09-29 16:08 UTC, F4lkr4m commented on server.ts
> +  const nameExtension = nameSplitted[nameSplitted.length - 1];
`nameSplitted.at(-1)`

2024-09-29 16:08 UTC, F4lkr4m commented on server.ts
> +app.listen(3000, () => {
Порт сверху же указывали...

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +  state: LandingState | AppState;
Landing у нас это HomePage

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +    if (appRoot === null) throw new Error('appRoot is null');
Фигурные и так везде по коду

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +    this.mode = 'app'; //todo роутер
дефолтное значение можно задать выше `mode: 'landing' | 'app' =  'app';`

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +  constructor(appRoot: Element | null) {
`(appRoot: Element) ` - вы должны из вне делать проверку, не нужно передавать нулл в конструктор. Вы либо при запуске приложения пишете что рута нет и все наебнулось и не создаете класс или создаете, если он есть

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +    if (this.mode === 'app') {
Делайте мапу 
```
const modeToView = {
app: MainApp,
home: HomePage,
}
```

и маппитесь просто 
`modeToView[this.mode]`

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +    if (document.location.href.endsWith('app')) {
Регулярку сделайте вместе этого

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +class LandingState {
Пробельная строка между классами и классы вообще в разные файлы разнесите

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +  isRegistrationDialogOpened: boolean;
Значения по умолчанию здесь можно задать и обойтись без конструктора и к классу ниже тоже самое

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +const appRoot = document.getElementById('app_root');
Сделайте отдельный файл и вынесите туда функцию инициализации всего приложения

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +export const initISS = () => {
ISS название которое не говорящее. Давай типа initStore

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/interfaceStateStore.ts
> +  console.log(interfaceStateStore?.state);
console.log'и не нужны нам в приложении, кроме необходимых логов о запуске и инициализации

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
В итоге будем именовать как chunks, а не containers?

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +        style="width: 100%; height: 58px; display: flex;  align-items: center; gap: 10px;"
Скажем нет инлайн стилям

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +    <div class="left_menu">
left-menu

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +        class="left__menu__header"
left-menu__header

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +        <div class="left_menu__left_elements">
left-menu__left-elements

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +            class="logo__left__menu_header"
left-menu__logo

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +        class="left__menu__body"
left-menu__body

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +          style="display: flex; align-items:center; gap: 50px; margin-left: 14px; margin-top: 30px"
Везде убрать инлайны

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +          class="first-level"
Этот класс для чего?

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +          {boardsStore.getWithFilters().map((board) => {
`boardsStore.getWithFilters().map(({ id, title }) => { ... })`

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/LeftPanel.tsx
> +            interfaceStateStore?.update();
`update `должен совершаться автоматически внутри `interfaceStateStore`, его не нужно вызывать каждый раз откуда угодно, иначе вы заебетесь разбираться кто его обновляет

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/NavBar.tsx
> +      style="padding-top:0"
Нет инлайн стилям!

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/NavBar.tsx
> +        getAppISS().isLeftPanelOpened = !getAppISS().isLeftPanelOpened;
вообще вам стоит делать что-то типа  `const store = getStore().homeStore;` и уже потом работать с функциями этого стора по типу `toggleLeftPanel`. Сейчас вы мешаете области работы и работаете с котом в мешке

2024-09-29 16:08 UTC, F4lkr4m commented on src/chunks/NavBar.tsx
> +            callback: () => {
Тут тоже ситуация вы берет `const { authStore } = getStore();` вызываете у него одну функцию `authStore.logout()` и дальше он там все делает, а что он там делает вам не важно

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/BoardCard.tsx
> +    <div class="left__menu__card__info">
board-card

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/BoardCard.tsx
> +          class="left__menu__card__name__title"
board-card__title

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/BoardCard.tsx
> +        class="board_delete_link"
board-card__link

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/BoardCard.tsx
> +        <div class="left__menu__card__name__text" style="font-size:12px;">
board-card__last-visit

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/BoardCard.tsx
> +        <div class="left__menu__card__name__subtext" style="font-size:12px;">
board-card__last-update

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/Button.tsx
> +          <div style="width:8px"></div>
инлайн стили

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/ModalDialog.tsx
> +    <div class="modal_dialog__back">
modal-dialog

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/ModalDialog.tsx
> +      <div class="modal_dialog">
modal-dialog-container

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/ModalDialog.tsx
> +        <div class="modal_dialog__title_block">
modal-dialog__title-block

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/ModalDialog.tsx
> +          <span class="modal_dialog__title">{props.title}</span>
modal-dialog__title

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/ModalDialog.tsx
> +        <hr style="margin-bottom:15px" />
Нет инлайнам

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/ModeSelect.tsx
> +      <div style="padding-left: 5px;flex-grow:1">Канбан</div>
Нет инлайнам

2024-09-29 16:08 UTC, F4lkr4m commented on src/components/ModeSelect.tsx
> +      <div style="padding-left: 5px;flex-grow:1">Канбан</div>
Тут не нужно передавать кастомный title?

2024-09-29 16:08 UTC, F4lkr4m commented on src/jsxCore/jsx-runtime/index.ts
> +  if (Array.isArray(children)) return children;
Фигурные скобки

2024-09-29 16:08 UTC, F4lkr4m commented on src/jsxCore/renderer.ts
> +            if (attrName.startsWith('ON_')) {
не хотите поменять на `@click` и трекать по `attrName.startsWith('@')`?

2024-09-29 16:08 UTC, F4lkr4m commented on src/jsxCore/renderer.ts
> +              const eventName = attrName.slice(3);
Надо сделать `prefix = 'ON_'` и у него вычислять длину `prefix.length`

2024-09-29 16:08 UTC, F4lkr4m commented on src/screens/Landing.tsx
> +      <div class="landing_contents">
home__content

2024-09-29 16:08 UTC, F4lkr4m commented on src/screens/Landing.tsx
> +                  <label for="description">Описание пользователя:</label>
Зачем вам сейчас описание? Мне кажется оно лишнее. Сделайте чтобы потом в профиле можно было заполнить, тут оно ни к чему

2024-09-29 16:08 UTC, F4lkr4m commented on src/screens/Landing.tsx
> +                <div class="form-field">
Вынесите форму в отдельный компонент и не забудьте про валидацию полей

2024-09-29 16:08 UTC, F4lkr4m commented on src/screens/MainApp.tsx
> +                        console.log(src.value);
Лишний лог

2024-09-29 16:08 UTC, F4lkr4m commented on src/screens/MainApp.tsx
> +                    const cb = getAppISS().boardDeleteDialogCallback;
Тут мясо происходит, но я уже говорил выше

2024-09-29 16:08 UTC, F4lkr4m commented on src/screens/MainApp.tsx
> +            style="display: flex; flex-direction: column; height: 427px; width: 272px; background-color:#F1F2F4; border-radius:12px; margin-top: 74px; margin-left: 14px;"
Нет инлайнам

2024-09-29 16:08 UTC, F4lkr4m commented on src/screens/MainApp.tsx
> +              class="board__card__title"
Где то я уже видел такой компонент

2024-09-29 16:08 UTC, F4lkr4m commented on src/stores/activeBoardStore.ts
> +    this.activeBoard = {
Сделайте отдельную папку с моками

2024-09-29 16:15 UTC, DeDxYk594 commented on src/chunks/LeftPanel.tsx
> +            interfaceStateStore?.update();
К следующему РК сделаем нормальное отслеживание

2024-09-29 16:16 UTC, DeDxYk594 commented on src/jsxCore/renderer.ts
> +            if (attrName.startsWith('ON_')) {
В jsx так нельзя синтаксически

2024-09-29 17:44 UTC, zhugeo commented on README.md
> +
Добавил!

2024-09-29 17:49 UTC, DeDxYk594 commented on src/stores/interfaceStateStore.ts
> +    if (appRoot === null) throw new Error('appRoot is null');
Линтер не запрещает так делать, если if и тело if'a находятся в одной строке :(
Так и не разобрался с тем, как сделать более строгий конфиг

2024-09-29 17:54 UTC, DeDxYk594 commented on src/stores/interfaceStateStore.ts
> +export const initISS = () => {
initStore: какой именно store?
Надо придумать другое название

2024-09-29 17:56 UTC, DeDxYk594 commented on src/chunks/LeftPanel.tsx
> +          class="first-level"
Хз

2024-09-29 17:57 UTC, DeDxYk594 commented on src/components/Button.tsx
> +          <div style="width:8px"></div>
Всё настолько строго, что даже для заглушки-разделителя надо делать отдельный класс??

2024-09-29 18:13 UTC, DeDxYk594 commented on src/chunks/LeftPanel.tsx
`containers`
Сорри, не сделал

2024-09-29 18:19 UTC, DeDxYk594 commented on .prettierrc
Prettier может отлавливать только синтаксические ошибки, а ESLint можно очень гибко настроить на проверку кода

2024-09-29 18:22 UTC, DeDxYk594 commented on src/stores/interfaceStateStore.ts
> +const appRoot = document.getElementById('app_root');
Нет. К 2 РК сделаем рефакторинг и вынесем, а пока оставим так

2024-09-29 18:23 UTC, zhugeo commented on src/chunks/LeftPanel.tsx
> +          class="first-level"
Переименовал

2024-09-29 18:23 UTC, DeDxYk594 commented on src/chunks/LeftPanel.tsx
> +          {boardsStore.getWithFilters().map((board) => {
Нет. Позже будут отрисовываться другие поля из Board, поэтому я бы оставил как есть

2024-09-29 18:28 UTC, DeDxYk594 commented on src/components/BoardCard.tsx
> +          class="left__menu__card__name__title"
Философию понял, сделал немного иначе

2024-09-29 21:46 UTC, F4lkr4m requested changes

2024-09-29 21:46 UTC, F4lkr4m commented on package.json
> +    "tslib": "^2.7.0",
Удалить

2024-09-29 21:46 UTC, F4lkr4m commented on src/App.tsx
> +fetch('/apiUrl')
Захардкодьте пока, вообще такое через .env делается

2024-09-29 21:46 UTC, F4lkr4m commented on src/apiHelper.ts
> +  apiRoot = apiRoot_;
Просто сделайте const API_ROOT = '...'

2024-09-29 21:46 UTC, F4lkr4m commented on src/containers/LoginDialog.tsx
> +              fetch(getApiUrl('/auth/login'), {
Так, нужно сделать либо функции декораторы, либо AJAX класс, так не пойдет, каждый раз писать параметры для fetch заебетесь

2024-09-29 21:46 UTC, F4lkr4m commented on src/containers/LoginDialog.tsx
> +              fetch(getApiUrl('/auth/login'), {
Также нужно сделать отдельные api функции 
по типу 
`const login = (payload: LoginPayload) => post('api/v1/login', payload, opts);`
И в отдельный файл

2024-09-29 21:46 UTC, F4lkr4m commented on src/containers/LoginDialog.tsx
> +                  if (res.status !== 200) {
200 в константу

2024-09-29 21:46 UTC, F4lkr4m commented on src/containers/LoginDialog.tsx
> +                .catch(() => {
Го использовать async функции

2024-09-29 21:46 UTC, F4lkr4m commented on src/containers/RegistrationDialog.tsx
> +                /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
Регулярку в константу, и регулярка у вас пиздец, разберите ее, или вас выдрочат на РК

2024-09-29 21:46 UTC, F4lkr4m commented on src/containers/RegistrationDialog.tsx
> +            const nicknameElem = document.getElementById(
Много повторений кода, сделайте хелпер 

`getElementById(id: string)`

2024-09-29 21:46 UTC, F4lkr4m commented on src/containers/RegistrationDialog.tsx
> +            if (!password || password.length < 8) {
8 в константу

2024-09-29 21:46 UTC, F4lkr4m commented on src/containers/RegistrationDialog.tsx
> +              fetch(getApiUrl('/auth/register'), {
Тут те же комменты, что и сверху

2024-09-30 11:04 UTC, DeDxYk594 commented on src/containers/LoginDialog.tsx
> +                .catch(() => {
Не получится без использования `tslib`

2024-09-30 11:05 UTC, DeDxYk594 commented on src/containers/RegistrationDialog.tsx
> +            const nicknameElem = document.getElementById(
Это не всегда безопасно

2024-09-30 11:39 UTC, F4lkr4m approved these changes

2024-09-30 15:43 UTC, merged