Добавлен профиль пользователя
frontend-park-mail-ru/2024_2_RPO pull request #7
Opened 2024-10-17 20:18 UTC by DeDxYk594

Делал Костя

2024-10-17 20:26 UTC, DeDxYk594 reviewed
Посмотрел изменения. В целом неплохо, но есть замечания, исправь их.
Ещё - переведи css на методологию БЭМ
Когда сделаешь, будем думать о дизайне

2024-10-17 20:26 UTC, DeDxYk594 commented on src/containers/UserProfile.tsx
> +              </button>
Кнопки надо заменить на наши
`<Button key="upload-button" icon="bi-images" callback=... />`

2024-10-17 20:26 UTC, DeDxYk594 commented on src/containers/UserProfile.tsx
> +    <ModalDialog key="Modal" isOpened={true}>
Добавь атрибут title
Тогда у тебя строчка будет выглядеть следующим образом:
<ModalDialog key="Modal" title="Мой профиль" isOpened={true}>

2024-10-17 20:26 UTC, DeDxYk594 commented on src/containers/UserProfile.tsx
> +        </div>
Это удали, оно делается в title

2024-10-17 20:26 UTC, DeDxYk594 commented on src/icons/kanban.svg
Все svg-шки удалить

2024-10-17 20:26 UTC, DeDxYk594 commented on src/index.scss
> +
Удалить, оно уже задаётся в `index.scss`

2024-10-17 20:26 UTC, DeDxYk594 commented on src/index.scss
> +}
Не задавай стили на какой-то тег, лучше навесь класс. Из-за этого плывёт вёрстка

2024-10-17 20:26 UTC, DeDxYk594 commented on src/index.scss
> +}
Это не будет использоваться, потому что заменяется нашим компонентом ModalDialog. Удали это и найди ещё неиспользуемые css в твоём PR

2024-10-17 20:26 UTC, DeDxYk594 commented on src/register.css
Удали этот файл

2024-10-17 20:26 UTC, DeDxYk594 commented on src/register.html
Удали этот файл

2024-10-17 20:26 UTC, DeDxYk594 commented on src/containers/UserProfile.tsx
> +              </button>
И в других местах тоже замени

2024-10-17 20:50 UTC, DeDxYk594 commented on src/index.scss
> +
И из-за того, что ты навесил стили на body, вёрстка поплыла

2024-10-20 11:49 UTC, DeDxYk594 commented on src/containers/UserProfile.tsx
> +                    // onclick=""
В button'e для обработки события нажатия используется атрибут `callback`
Это можно посмотреть в файле `src/components/Button.tsx`

2024-10-20 11:49 UTC, DeDxYk594 commented on src/index.scss
> +
CSS, связанный с модальным диалогом, уже написан для компонента `ModalDialog`. Это удали

2024-10-20 11:49 UTC, DeDxYk594 commented on src/index.scss
> +}
Кнопку загрузки сделаем так, как нарисовано в figma, соответственно, эти классы не нужны

2024-10-20 11:49 UTC, DeDxYk594 commented on src/index.scss
> +}
Аналогично: эти классы не нужны

2024-10-20 14:59 UTC, DeDxYk594 reviewed
Норм

2024-10-20 14:59 UTC, DeDxYk594 commented on src/containers/UserPopup.tsx
> +      <tbody>
Давай без таблиц пж, лучше flexbox

2024-10-20 14:59 UTC, DeDxYk594 commented on src/containers/UserPopup1.tsx
> +
Этот jsdoc неактуален

2024-10-20 14:59 UTC, DeDxYk594 commented on src/containers/UserPopup1.tsx
> +  children?: JsxNode;
Зачем children компоненту, который используется только в одном месте?

2024-10-20 14:59 UTC, DeDxYk594 commented on src/index.scss
> +.popup-image {
`.user-popup__user-avatar`

2024-10-20 14:59 UTC, DeDxYk594 commented on src/index.scss
> +
Всё, что связано с одним блоком БЭМ, размещай в CSS-файле рядом, чтобы оно не было раскидано по всему файлу

2024-10-20 14:59 UTC, DeDxYk594 commented on src/index.scss
> +  position: absolute;
Лучше `position: fixed`

2024-10-20 14:59 UTC, DeDxYk594 commented on src/index.scss
> +  justify-content: space-around;
Зачем в нём flex?

2024-10-21 15:40 UTC, DeDxYk594 reviewed
Добавил несколько замечаний, подправь. Скоро можно будет сливать ветки

2024-10-21 15:40 UTC, DeDxYk594 commented on .vscode/settings.json
Лучше сделай в этом файле настройку, которая отключает автосохранение (потому что webpack в режиме watch не вытянет автосохранение)

2024-10-21 15:40 UTC, DeDxYk594 commented on src/components/Button.tsx
> +  transparent: '#C15DF3',
Сделай их как css-переменные и вынеси в css:
```css
:root{
    --accent-color: #0070F0;
    -- default-color: #F6F5FA;
    ...
}
```
И создай классы с модификаторами для кнопок:
```css
.button {}
.button__accent {
    background-color: var(--accent-color);
}
```
Цвета не должны храниться в js

2024-10-21 15:40 UTC, DeDxYk594 commented on src/components/Button.tsx
> +      <div class="button" ON_click={props.callback} style={{ backgroundColor }}>
А здесь используй атрибут `className` для задания имени класса.
`<div className={["button",`button__${props.variant??"default"}`]} ...>`

Атрибут `className` склеит этот массив в строку и всё назначит

2024-10-21 15:40 UTC, DeDxYk594 commented on src/containers/UserPopup.tsx
> +  children?: JsxNode;
1) Скорее всего, этому компоненту не нужны `children`;
2) Если бы он был нужен, `children` должен иметь тип `JsxSubtree`

2024-10-21 15:40 UTC, DeDxYk594 commented on src/containers/UserPopup.tsx
> + */
Переделай jsdoc

2024-10-21 15:41 UTC, DeDxYk594 commented on src/icons/x-lg.svg
Иконки в виде svg не нужны

2024-10-21 15:44 UTC, DeDxYk594 commented on src/screens/MainApp.tsx
> +
Лучше такие строчки с импортами удаляй без сожаления, они точно не пригодятся

2024-10-21 16:29 UTC, F4lkr4m commented on .vscode/settings.json
Лишний файл, его в гитигнор

2024-10-21 16:29 UTC, F4lkr4m commented on index.html
> +    <!-- <link rel="icon" href="favicon.ico"> -->
Лишний коммент

2024-10-21 16:30 UTC, F4lkr4m commented on src/components/Button.tsx
> +  transparent: '#C15DF3',
Плюсую с переменными

2024-10-21 16:30 UTC, F4lkr4m commented on src/components/Button.tsx
> +  const backgroundColor = props.variant ? colorMap[props.variant] : '#F6F5FA'; // Цвет по умолчанию — белый
'#F6F5FA' - дефолтный цвет в константу

2024-10-21 16:31 UTC, F4lkr4m commented on src/containers/UserPopup.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Зачем эта строчка?

2024-10-21 16:31 UTC, F4lkr4m commented on src/containers/UserPopup.tsx
> +            <div class="user-popup__info">@KarlMarkssss</div>
Что за хардкод?

2024-10-21 16:31 UTC, F4lkr4m commented on src/containers/UserProfile.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Он же по идее не должен ругаться, тк идет экспорт

2024-10-21 16:32 UTC, F4lkr4m commented on src/containers/UserProfile.tsx
> +            <Button
Рендерим кнопки из массива пропсов, чтобы избежать копипасты

2024-10-21 16:32 UTC, F4lkr4m commented on src/containers/UserProfile.tsx
> +          {/* <Button
Комменты все лишние удаляем

2024-10-21 16:33 UTC, F4lkr4m requested changes
Надо поправить

2024-10-22 12:59 UTC, F4lkr4m approved these changes

2024-10-22 13:00 UTC, merged