Разработка моков и функций запросов
frontend-park-mail-ru/2024_2_RPO pull request #8
Opened 2024-10-20 12:33 UTC by DeDxYk594

- [ ] Сделать функцию-шорткат для запросов
- [ ] Реализовать функции для доступа к ручкам, которые нужны для РК2
- [ ] Сделать моки для этих функций

2024-10-21 16:38 UTC, F4lkr4m requested changes

2024-10-21 16:38 UTC, F4lkr4m commented on src/App.tsx
> +loadBoard(2);
2?

2024-10-21 16:38 UTC, F4lkr4m commented on src/api/boards.ts
> +      credentials: 'include',
Стоит эту настройку сделать по умолчанию

2024-10-21 16:38 UTC, F4lkr4m commented on src/api/boards.ts
> +      credentials: 'include',
И стоило бы сделать отдельные обертки для fetch, которые его донастраивают, например функции заготовки `get(url, opts)` `post(url, opts)` `put(url, opts)`

2024-10-21 16:38 UTC, F4lkr4m commented on src/api/boards.ts
> +    if (response.status === HTTP_STATUS_OK) {
`switch (response.status) {}`

2024-10-21 16:38 UTC, F4lkr4m commented on src/api/boards.ts
> +    alert('An error occurred while fetching boards');
Давайте не использовать алерты, будем логгировать в консоль. А для пользовательских ошибок надо сделать нормальный снекбар

2024-10-21 16:38 UTC, F4lkr4m commented on src/api/boards.ts
> +    if (response.status === HTTP_STATUS_OK) {
Тоже `switch() {}`

2024-10-21 16:38 UTC, F4lkr4m commented on src/api/boards.ts
> +    // return [];
//

2024-10-21 16:38 UTC, F4lkr4m commented on src/api/users.ts
>        method: 'POST',
Это все стандартные настройки post запроса, сделайте декоратор

2024-10-21 16:38 UTC, F4lkr4m commented on src/components/KanbanCard.tsx
> +      {props.coverUrl !== undefined ? (
`props.coverUrl ? //... : //...`

2024-10-21 16:38 UTC, F4lkr4m commented on src/containers/KanbanBoard.tsx
> +  console.log(activeBoardStore);
Лишний лог

2024-10-21 16:43 UTC, DeDxYk594 commented on src/App.tsx
> +loadBoard(2);
Когда разработаем роутер, сделаем, чтобы оно доставалось из роута

2024-10-21 16:43 UTC, DeDxYk594 commented on src/api/boards.ts
> +      credentials: 'include',
Ок, сделаем

2024-10-26 10:37 UTC, DeDxYk594 commented on src/api/boards.ts
> +    alert('An error occurred while fetching boards');
Потом сделаем snackbar

2024-10-26 17:02 UTC, merged